version: '3'

env:
  OS:
    sh: uname | tr '[:upper:]' '[:lower:]'
  ARCH:
    sh: uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/'

tasks:
  install-common:
    cmds:
      - sudo apt-get install -y flatpak python3-pygments apt-transport-https ca-certificates gnupg

  install-flatpaks:
    deps:
      - setup-common
    cmds:
      - flatpak -v remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      - flatpak install -y flathub com.anydesk.Anydesk com.github.tchx84.Flatseal com.rtosta.zapzap org.telegram.desktop com.valvesoftware.Steam com.visualstudio.code com.slack.Slack org.ferdium.Ferdium org.clementine_player.Clementine org.cryptomator.Cryptomator org.darktable.Darktable org.gnome.meld org.kde.kdenlive org.nomacs.ImageLounge org.qbittorrent.qBittorrent org.remmina.Remmina net.mullvad.MullvadBrowser org.keepassxc.KeePassXC

  install-zsh:
    deps:
      - install-flatpaks
    cmds:
      - sudo apt install -y zsh
      - sudo chsh -s /bin/zsh
    vars:
      RUNZSH: false
    status:
      - test -f /bin/zsh

  install-nix:
    deps:
      - install-zsh
    cmds:
      - sh <(curl -L https://nixos.org/nix/install) --daemon --yes
      - source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      - nix-shell -p nix-info --run "nix-info -m"
    status:
      - test -d /nix

  install-docker:
    dir: /tmp
    deps:
      - install-nix
    cmds:
      - sudo install -m 0755 -d /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/{{.DISTRO}}/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      - sudo chmod a+r /etc/apt/keyrings/docker.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{.DISTRO}} {{.VERSION_CODENAME}} stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - sudo apt-get update
      - sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    vars:
      DISTRO:
        sh: . /etc/os-release && echo "$NAME" | tr '[:upper:]' '[:lower:]'
      VERSION_CODENAME:
        sh: . /etc/os-release && echo "$VERSION_CODENAME"
    status:
      - test -f /usr/bin/dockerd

  install-sway:
    deps:
      - install-docker
    cmds:
      - sudo apt install -y sway xdg-desktop-portal-wlr swaylock
      - pip install --break-system-packages khayyam
    status:
      - test -f /usr/bin/sway

  config-logind-conf:
    deps:
      - install-sway
    cmds:
      - sudo mkdir -p /etc/systemd/logind.conf.d
      - cmd: sudo ln -s $HOME/.dotfiles/logind.conf.d/90-custom.conf /etc/systemd/logind.conf.d/90-custom.conf
        ignore_error: true
    status:
      - test -f /etc/systemd/logind.conf.d/90-custom.conf

  install-tailscale:
    dir: /tmp
    deps:
      - install-logind-conf
    cmds:
      - curl -fsSL https://tailscale.com/install.sh | sh
      - tailscale version
    status:
      - test -f /usr/bin/tailscale

  install-once:
    deps:
      - install-tailscale

# --------------------------------------------- Install or update ----------------------------------------

  install-or-update-mullvad:
    dir: /tmp
    cmds:
      - curl -sSL -o mullvad.deb https://mullvad.net/en/download/app/deb/latest
      - sudo dpkg -i mullvad.deb
      - rm mullvad.deb
      - mullvad version

  install-or-update-windscribe:
    dir: /tmp
    deps:
      - install-or-update-mullvad
    cmds:
      - curl -sSL -o windscribe.deb https://windscribe.com/install/desktop/linux_deb_x64
      - cmd: sudo dpkg -i windscribe.deb
        ignore_error: true
      - sudo apt install -f -y
      - rm windscribe.deb

  install-or-update:
    deps:
      - install-or-update-windscribe

# ------------------------------------------------------------------------------------------------------

  install-all:
    deps:
      - install-once
      - install-or-update
